name: "Deploy Pipeline"
on:
  workflow_run:
    workflows: ["Build Pipeline"]
    branches: ["main"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - run: npm i
    - run: npm run update-docs
